import type {
  MinuteTransaction,
  MinutePackage,
  UserProfile,
  AuditLogEntry,
  FinancialLedgerEntry,
  Coupon,
} from '../types/index.js';
export const securityConfig = {
  wafEnabled: true,
  rateLimiterEnabled: true,
  promptInjectionGuard: true,
  financialProtection: true,
  sanitizerEnabled: true,
  strictHeaders: true,
  maxRequestsPerMinute: 60,
  maxAiRequestsPerMinute: 20,
  maxAuthAttemptsPerMinute: 10,
};

export const securityMetrics = {
  totalRequestsChecked: 15200,
  blockedAttacks: 18,
  rateLimitHits: 4,
  promptInjectionsBlocked: 3,
  sanitizedInputs: 94,
  lastScanTime: new Date().toISOString(),
  threatScore: 'BAIXO (0.01%)',
  serverUptimeStart: Date.now(),
};

export const blacklistedIPs = new Set<string>(['185.220.101.5', '198.51.100.42']);
export const whitelistedIPs = new Set<string>(['127.0.0.1', '::1', '192.168.1.100']);
export const processedPaymentIds = new Set<string>();
export const userDailyAiUsage: Record<string, { count: number; resetAt: number }> = {};

export const usersDb: Record<string, UserProfile & { balance: number }> = {
  'usr-client-1': {
    id: 'usr-client-1',
    name: 'Maria Silva',
    birthFullName: 'Maria Silva de Oliveira',
    email: 'maria.silva@exemplo.com',
    birthDate: '1992-05-14',
    birthTime: '14:30',
    doesNotKnowBirthTime: false,
    role: 'user',
    status: 'active',
    minuteBalance: 150,
    balance: 150.0,
    termsAccepted: true,
    privacyAccepted: true,
    birthDataConsent: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    favorites: ['cons-1', 'cons-3'],
  },
  'usr-consultant-1': {
    id: 'usr-consultant-1',
    name: 'Mantra Elena',
    birthFullName: 'Mantra Elena Santos',
    email: 'mantra.elena@exemplo.com',
    birthDate: '1988-11-20',
    birthTime: '08:15',
    doesNotKnowBirthTime: false,
    role: 'employee',
    status: 'active',
    minuteBalance: 850,
    balance: 850.0,
    termsAccepted: true,
    privacyAccepted: true,
    birthDataConsent: true,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    favorites: [],
  },
  'usr-support-1': {
    id: 'usr-support-1',
    name: 'Atendimento Suporte',
    birthFullName: 'Atendimento Suporte',
    email: 'suporte@oraculos.com',
    birthDate: '1995-01-01',
    birthTime: null,
    doesNotKnowBirthTime: true,
    role: 'support',
    status: 'active',
    minuteBalance: 0,
    balance: 0.0,
    termsAccepted: true,
    privacyAccepted: true,
    birthDataConsent: true,
    createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 86400000).toISOString(),
    favorites: [],
  },
  'usr-admin-1': {
    id: 'usr-admin-1',
    name: 'Administrador Geral',
    birthFullName: 'Administrador Geral',
    email: 'admin@oraculos.com',
    birthDate: '1985-06-10',
    birthTime: '12:00',
    doesNotKnowBirthTime: false,
    role: 'admin',
    status: 'active',
    minuteBalance: 0,
    balance: 0.0,
    termsAccepted: true,
    privacyAccepted: true,
    birthDataConsent: true,
    createdAt: new Date(Date.now() - 365 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 365 * 86400000).toISOString(),
    favorites: [],
  },
  'usr-superadmin-1': {
    id: 'usr-superadmin-1',
    name: 'Superadmin Mestre',
    birthFullName: 'Superadmin Mestre',
    email: 'superadmin@oraculos.com',
    birthDate: '1980-03-25',
    birthTime: '06:00',
    doesNotKnowBirthTime: false,
    role: 'superadmin',
    status: 'active',
    minuteBalance: 0,
    balance: 0.0,
    termsAccepted: true,
    privacyAccepted: true,
    birthDataConsent: true,
    createdAt: new Date(Date.now() - 365 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 365 * 86400000).toISOString(),
    favorites: [],
  },
};

export const auditLogs: AuditLogEntry[] = [
  {
    id: 'log-001',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    userId: 'usr-admin-1',
    userName: 'Administrador Geral',
    userRole: 'admin',
    action: 'SYSTEM_BOOT',
    details: 'Inicialização segura dos serviços e WAF do ORACULOS.TS',
    ip: '127.0.0.1',
    status: 'SUCCESS',
  },
];

export const couponsDb: Record<string, Coupon> = {
  ORACULO10: {
    id: 'coup-1',
    code: 'ORACULO10',
    type: 'bonus_fixed',
    value: 10,
    active: true,
    expiresAt: '2028-12-31T23:59:59.000Z',
    maxUses: 1000,
    currentUses: 5,
    maxUsesPerUser: 1,
    userUsesCount: {},
    eligibleProducts: ['all'],
    createdAt: new Date().toISOString(),
    createdBy: 'system',
  },
};
